/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "movies_constants.h"

namespace movies {

const moviesConstants g_movies_constants;

moviesConstants::moviesConstants() {
}

} // namespace

