/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef movies_CONSTANTS_H
#define movies_CONSTANTS_H

#include "movies_types.h"

namespace movies {

class moviesConstants {
 public:
  moviesConstants();

};

extern const moviesConstants g_movies_constants;

} // namespace

#endif
